Game is slight bugged when check_for_three() is called, but only in scenarios where a win is already guraunteed.
